# Generated by Django 3.1.3 on 2021-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FilePathField(default='', path='E:\\Myportfolio\\myportfolio/static/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='', path='E:\\Myportfolio\\myportfolio/static/img'),
        ),
    ]
